// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wfhwytncnnyigjukffjv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndmaHd5dG5jbm55aWdqdWtmZmp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MDY2MDcsImV4cCI6MjA2NDE4MjYwN30.N2OgZXTUuAe1WSL1QFDWGVPaIx6OswGWbxJKQtB11iI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);